name: Buld and Push

on:
  push:
    branches:
    - main
    paths:
    - 'services/api-gateway/**'


jobs:
  build:
    name: Continuos Integration - API Gateway
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v6
        with: 
          working_directory: ./services/api-gateway
        env:
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
